# Numpy

In [1]:
#importing numpy in python
import numpy as np
print(np.__version__)

1.23.1


## 1)Numpy array

In [27]:
#Creating an array object
arr = np.array([10, 20, 30])
arr

array([10, 20, 30])

In [5]:
#Printing type
type(arr)

numpy.ndarray

In [6]:
#Printing number of dimensions (axes)
arr.ndim

1

In [7]:
#printng shape
arr.shape

(3,)

In [29]:
#Printing size (Total number of elements)
arr.size

3

In [9]:
#Printing datatype
arr.dtype

dtype('int32')

In [28]:
#returns the size (in bytes) of a single element in an array.
arr.itemsize

4

In [30]:
#returns the total number of bytes consumed by the elements in the array
arr.nbytes

12

### 1.1 Dimensions in arrays

In [19]:
#0-D array
arr = np.array(34)
print(arr)
print('Array dimension:', arr.ndim)
print('Array shape:', arr.shape)
print('Array size:', arr.size)

34
Array dimension: 0
Array shape: ()
Array size: 1


In [20]:
#1-D array
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
arr = np.array([12, 34, 56, 78])
print(arr)
print('Array dimension:', arr.ndim)
print('Array shape:', arr.shape)
print('Array size:', arr.size)

[12 34 56 78]
Array dimension: 1
Array shape: (4,)
Array size: 4


In [23]:
#2-D array
#An array that has 1-D arrays as its elements is called 2-D array.
arr = np.array([[12, 34], [33, 89], [45, 28]])
print(arr)
print('Array dimension:', arr.ndim)
print('Array shape:', arr.shape)
print('Array size:', arr.size)

[[12 34]
 [33 89]
 [45 28]]
Array dimension: 2
Array shape: (3, 2)
Array size: 6


In [26]:
#3-D array
#An array that has 2-D arrays as its elements is called 3-D array.
arr = np.array([[[1, 2, 8], [3, 4, 9]], [[6, 7, 3], [8,9, 2]]])
print(arr)
print('Array dimension:', arr.ndim)
print('Array shape:', arr.shape)
print('Array size:', arr.size)

#(2, 2, 3) Means: The array has 2 2D arrys, then, 2 1D arrys within each 2D arry and then 3 elements within each 1D array.

[[[1 2 8]
  [3 4 9]]

 [[6 7 3]
  [8 9 2]]]
Array dimension: 3
Array shape: (2, 2, 3)
Array size: 12


### 1.2 Accessing specific array elements

In [ ]:
#Index starts from 0

In [43]:
#1D array
arr = np.array([34, 56, 78, 99, 54])
print(arr)
print(arr[0])
print(arr[arr.size-1])

[34 56 78 99 54]
34
54


In [50]:
#2D array
ar2 = np.array([[56, 78, 33], [90, 23, 85]])
print(ar2)
print(ar2.shape)
print(ar2[0, 2]) #[r, c]
print(ar2[1, 1])

[[56 78 33]
 [90 23 85]]
(2, 3)
33
23


In [52]:
#3D array
ar3 = np.array([[[8, 7, 9, 3], [2, 4, 0, 1], [8, 7, 9, 3]], [[8, 7, 9, 3], [2, 4, 0, 1], [8, 7, 9, 3]]])
print(ar3.shape)
print(ar3)

print(ar3[1, 0, 2])

(2, 3, 4)
[[[8 7 9 3]
  [2 4 0 1]
  [8 7 9 3]]

 [[8 7 9 3]
  [2 4 0 1]
  [8 7 9 3]]]
9


### 1.3 Slicing

In [ ]:
#In slicing, [start:end:step]
#end index is exclusive
#By default step is 1
#Negative index starts from -1

In [57]:
#1D array
arr = np.array([34, 56, 78, 99, 54])
arr[1:4]

array([56, 78, 99])

In [58]:
arr[:4:2]

array([34, 78])

In [59]:
#2D array
#arr[s:e:st, s:e:st]
ar2 = np.array([[56, 78, 33], 
                [90, 23, 85]])
ar2[1, :]

array([90, 23, 85])

In [60]:
ar2[:, 2]

array([33, 85])

In [64]:
ar2[:, ::2]

array([[56, 33],
       [90, 85]])

In [66]:
#3D array
#arr[s:e:st, s:e:st, s:e:st]
ar3 = np.array([[[8, 7, 9, 3], 
                 [2, 4, 0, 1],
                 [8, 7, 9, 3]],
                [[8, 7, 9, 3],
                 [2, 4, 0, 1],
                 [8, 7, 9, 3]]])

ar3[1, 1, :]

array([2, 4, 0, 1])

In [67]:
ar3[0, :, :]

array([[8, 7, 9, 3],
       [2, 4, 0, 1],
       [8, 7, 9, 3]])

In [68]:
ar3[1, :2, 1:3]

array([[7, 9],
       [4, 0]])

In [69]:
ar3[1, :3, ::2]

array([[8, 9],
       [2, 0],
       [8, 9]])

### 1.4 Different types of arrays

In [70]:
#Creates an array filled with zeros.
ar2 = np.zeros((3, 4))
ar2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
ar1 = np.zeros((1, 7))
ar1

array([[0., 0., 0., 0., 0., 0., 0.]])

In [72]:
ar3 = np.zeros((3, 2, 5))
ar3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [74]:
# Creates an array filled with ones.
ar = np.ones((4, 2))
ar

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [75]:
# Creates an array without initializing its elements to any particular value
ar = np.empty((2, 3))
ar

array([[4.24399158e-314, 6.36598738e-314, 1.90979621e-313],
       [1.48539705e-313, 1.69759663e-313, 4.24399159e-314]])

In [76]:
# Creates an array filled with a specific value.
ar = np.full((3, 2), 7)
ar

array([[7, 7],
       [7, 7],
       [7, 7]])

In [82]:
# Creates a square identity matrix
ar = np.identity(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
# Alternative way for identity matrix
ar = np.eye(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
#  Creates an array filled with random values between 0 and 1.
ar = np.random.random((4, 3))
ar

array([[0.6516711 , 0.60258966, 0.65254672],
       [0.62604753, 0.29127523, 0.78790065],
       [0.29120832, 0.88705696, 0.86361618],
       [0.54723982, 0.21870999, 0.24761215]])

In [102]:
# Random Integer values betwwn given range
# end index exclusive
ar = np.random.randint(0, 256, size=(3,2))
ar

array([[162, 230],
       [198, 201],
       [ 54,  76]])

In [103]:
#Creating a sequential arry with steps
# (start, end, step) 
# end is exclusive

np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [118]:
# linspace() function in NumPy is used to create an array of evenly spaced values within a specified range.
#It takes in three parameters: start, stop, and num.
# The linspace() function divides the interval between start and stop into num equally spaced values and
# returns an array containing those values.
np.linspace(1, 10, 6)


array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

### 1.5 Creating copy

In [106]:
#copy() used to create a deep copy of an array.
#It returns a new array that is a separate copy of the original array, with its own data and memory.

ar = np.random.randint(1, 10, (3, 2))

arc = ar.copy()
arc[1, 0] = 0

print(arc)
print(ar)

[[3 2]
 [0 8]
 [7 7]]
[[3 2]
 [9 8]
 [7 7]]


### 1.6 Mathematical operations

In [4]:
arr = np.array([34, 6, 89, 13, 67, 11])
arr

array([34,  6, 89, 13, 67, 11])

In [110]:
arr + 10

array([44, 16, 99, 23, 77, 21])

In [111]:
arr - 10

array([24, -4, 79,  3, 57,  1])

In [112]:
arr * 10

array([340,  60, 890, 130, 670, 110])

In [113]:
arr / 10

array([3.4, 0.6, 8.9, 1.3, 6.7, 1.1])

In [5]:
arr % 10

array([4, 6, 9, 3, 7, 1], dtype=int32)

In [115]:
arr ** 10

array([ 1723237376,    60466176, -2024127311,   419538377,  1333128745,
         167620825], dtype=int32)

#### 1.6.1 Arithmetic operations

In [58]:
# For performing these operations arrays must be of same shape.
# Can be performed on any number of arrays.
arr1 = np.array([34, 12, 7, 10, 3])
arr2 = np.array([-4, 5, 67, 2, 11])

In [14]:
# Addition
print(np.add(arr1, arr2))
print(arr1 + arr2)

[30 17 74 12 14]
[30 17 74 12 14]


In [15]:
# Subtraction
print(np.subtract(arr1, arr2))
print(arr1 - arr2)

[ 38   7 -60   8  -8]
[ 38   7 -60   8  -8]


In [16]:
# Multiplication
print(np.multiply(arr1, arr2))
print(arr1 * arr2)

[-136   60  469   20   33]
[-136   60  469   20   33]


In [17]:
# Division
print(np.divide(arr1, arr2))
print(arr1 / arr2)

[-8.5         2.4         0.10447761  5.          0.27272727]
[-8.5         2.4         0.10447761  5.          0.27272727]


In [18]:
# Exponentiation
print(np.power(arr1, 2))
print(arr1 ** 2)

[1156  144   49  100    9]
[1156  144   49  100    9]


In [19]:
# Modulo
print(np.mod(arr1, arr2))
print(arr1 % arr2)

[-2  2  7  0  3]
[-2  2  7  0  3]


In [135]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[1, 2, 3], [3, 4, 5]])
arr3 = np.array([[1, 2, 3], [3, 4, 5]])
arr4 = np.array([[1, 2, 3], [3, 4, 5]])
arr5 = np.array([[1, 2, 3], [3, 4, 5]])

arr1 + arr2 + arr3 + arr4 + arr5

array([[ 5, 10, 15],
       [15, 20, 25]])

In [20]:
# Square root
np.sqrt(arr1)

array([5.83095189, 3.46410162, 2.64575131, 3.16227766, 1.73205081])

In [59]:
# Cube root
np.cbrt(arr1)

array([3.2396118 , 2.28942849, 1.91293118, 2.15443469, 1.44224957])

In [22]:
# Absolute value
arr = np.array([12, 32, 78, -45, 0 -27])
np.abs(arr)

array([12, 32, 78, 45, 27])

In [23]:
# Negative value i.e it performs negation (sign change)
np.negative(arr)

array([-12, -32, -78,  45,  27])

#### 1.6.2 Trignometric Functions

In [24]:
arr

array([ 12,  32,  78, -45, -27])

In [25]:
#Sine
np.sin(arr)

array([-0.53657292,  0.55142668,  0.51397846, -0.85090352, -0.95637593])

In [26]:
# Cosine
np.cos(arr)

array([ 0.84385396,  0.83422336, -0.85780309,  0.52532199, -0.29213881])

In [27]:
# Tangent
np.tan(arr)

array([-0.63585993,  0.66100604, -0.59918   , -1.61977519,  3.2737038 ])

In [28]:
# Inverse sine
np.arcsin(arr)

C:\Users\User\AppData\Local\Temp\ipykernel_5080\520965174.py:2: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr)


array([nan, nan, nan, nan, nan])

In [29]:
# Inverse cosine
np.arccos(arr)

C:\Users\User\AppData\Local\Temp\ipykernel_5080\339456621.py:2: RuntimeWarning: invalid value encountered in arccos
  np.arccos(arr)


array([nan, nan, nan, nan, nan])

In [30]:
# Inverse tangent
np.arctan(arr)

array([ 1.48765509,  1.53955649,  1.55797652, -1.54857776, -1.53377621])

#### 1.6.3 Exponential and logarithmic functions

In [36]:
arr[3] = 0
arr

array([ 12,  32,  78,   0, -27])

In [37]:
#Exponential 
np.exp(arr)

array([1.62754791e+05, 7.89629602e+13, 7.49841700e+33, 1.00000000e+00,
       1.87952882e-12])

In [38]:
#Natural logarithm i.e log to the base e
np.log(arr)

C:\Users\User\AppData\Local\Temp\ipykernel_5080\286491332.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)
C:\Users\User\AppData\Local\Temp\ipykernel_5080\286491332.py:2: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([2.48490665, 3.4657359 , 4.35670883,       -inf,        nan])

In [39]:
#Base 10 logarithm 
np.log10(arr)

C:\Users\User\AppData\Local\Temp\ipykernel_5080\3364299638.py:2: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)
C:\Users\User\AppData\Local\Temp\ipykernel_5080\3364299638.py:2: RuntimeWarning: invalid value encountered in log10
  np.log10(arr)


array([1.07918125, 1.50514998, 1.8920946 ,       -inf,        nan])

In [40]:
#Base 2 logarithm 
np.log2(arr)

C:\Users\User\AppData\Local\Temp\ipykernel_5080\1358989749.py:2: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)
C:\Users\User\AppData\Local\Temp\ipykernel_5080\1358989749.py:2: RuntimeWarning: invalid value encountered in log2
  np.log2(arr)


array([3.5849625 , 5.        , 6.28540222,       -inf,        nan])

#### 1.6.4 Rounding and floor/ceiling functions

In [54]:
arr = np.array([12.345, 56.38, -0.67, 0.0023, 23.9845])

In [56]:
# Round to nearest integer
np.round(arr)

array([12., 56., -1.,  0., 24.])

In [57]:
# Round with specified number of decimals
np.round(arr, 2)

array([12.34, 56.38, -0.67,  0.  , 23.98])

In [44]:
# Round up
np.ceil(arr)

array([13., 57., -0.,  1., 24.])

In [45]:
# Round down
np.floor(arr)

array([12., 56., -1.,  0., 23.])

In [46]:
# Truncate decimal places
np.trunc(arr)

array([12., 56., -0.,  0., 23.])

#### 1.6.5 Statistical functions

In [47]:
arr = np.array([ 12,  32,  78,   0, -27])

In [48]:
# Mean: 
np.mean(arr)

19.0

In [49]:
# Median: 
np.median(arr)

12.0

In [50]:
# Standard deviation: 
np.std(arr)

35.14541221838208

In [51]:
# Variance: 
np.var(arr)

1235.2

In [52]:
# Maximum value: 
np.max(arr)

78

In [53]:
# Minimum value: 
np.min(arr)

-27

#### 1.6.6 Bit-wise operations

In [60]:
arr1 = np.array([34, 12, 7, 10, 3])
arr2 = np.array([-4, 5, 67, 2, 11])

In [61]:
# Bit-wise AND: 
np.bitwise_and(arr1, arr2)

array([32,  4,  3,  2,  3])

In [62]:
# Bit-wise OR: 
np.bitwise_or(arr1, arr2)

array([-2, 13, 71, 10, 11])

In [63]:
# Bit-wise XOR: 
np.bitwise_xor(arr1, arr2)

array([-34,   9,  68,   8,   8])

In [65]:
# Bit-wise NOT: 
np.bitwise_not(arr1)

array([-35, -13,  -8, -11,  -4])

#### 1.6.7 Comparison functions

In [68]:
arr1 = np.array([34, 12, 7, 10, 3])
arr2 = np.array([-4, 5, 67, 2, 11])

##### Elementwise comparison

In [67]:
np.equal(arr1, arr2)

array([False, False, False, False, False])

In [69]:
np.not_equal(arr1, arr2)

array([ True,  True,  True,  True,  True])

In [70]:
np.less(arr1, arr2)

array([False, False,  True, False,  True])

In [71]:
np.less_equal(arr1, arr2)

array([False, False,  True, False,  True])

In [72]:
np.greater(arr1, arr2)

array([ True,  True, False,  True, False])

In [73]:
np.greater_equal(arr1, arr2)

array([ True,  True, False,  True, False])

In [74]:
# Logical AND: 
np.logical_and(arr1, arr2)

array([ True,  True,  True,  True,  True])

In [75]:
# Logical OR: 
np.logical_or(arr1, arr2)

array([ True,  True,  True,  True,  True])

In [76]:
# Logical XOR: 
np.logical_xor(arr1, arr2)

array([False, False, False, False, False])

In [78]:
# Logical NOT: 
np.logical_not(arr1)

array([False, False, False, False, False])

#### 1.6.8 Linear algebra functions

In [83]:
arr1 = np.array([[2, 3, 4], 
                 [5, 6, 7]])

In [84]:
arr2 = np.array([[3, 4], 
                 [6, 7],
                 [6, 7]])

In [85]:
#Matrix multiplication 
#For matrix multiplication col of 1st matrix and row of 2nd matrix should be same.
arr1 @ arr2

array([[ 48,  57],
       [ 93, 111]])

In [86]:
arr2 @ arr1

array([[26, 33, 40],
       [47, 60, 73],
       [47, 60, 73]])

In [87]:
np.matmul(arr1, arr2) #same as arr1 @ arr2

array([[ 48,  57],
       [ 93, 111]])

In [88]:
# Dot product: 
np.dot(arr1, arr2)

array([[ 48,  57],
       [ 93, 111]])

In [98]:
#Cross product:
'''Note:
In cross product, for 1D array, shape should be (3,), and
for 2D array, shape should be (N, 3)
'''
arr3 = np.array([[2, 5, -2], 
                 [0, 2, 3]])
np.cross(arr1, arr3)

array([[-26,  12,   4],
       [  4, -15,  10]])

In [91]:
#Determinant is always a square matrix
arr = np.array([[2,3, 5],
                [5, 2, 0],
                [1, -4, 2]])

In [92]:
#Determinant
np.linalg.det(arr)

-131.99999999999997

In [93]:
#Eigenvalues: 
np.linalg.eigvals(arr)

array([-4.04503859+0.j       ,  5.0225193 +2.7215563j,
        5.0225193 -2.7215563j])

In [94]:
#Matrix inverse: 
np.linalg.inv(arr)

array([[-0.03030303,  0.1969697 ,  0.07575758],
       [ 0.07575758,  0.00757576, -0.18939394],
       [ 0.16666667, -0.08333333,  0.08333333]])

In [95]:
# Singular Value Decomposition: 
np.linalg.svd(arr)

(array([[-0.79285756,  0.30151134,  0.52959211],
        [-0.60622325, -0.30151134, -0.7359241 ],
        [ 0.06221144,  0.90453403, -0.42183874]]),
 array([7.08757278, 4.69041576, 3.97068156]),
 array([[-0.64262055, -0.54177432, -0.54177432],
        [ 0.        , -0.70710678,  0.70710678],
        [-0.76618459,  0.45440135,  0.45440135]]))

### 1.7 Reorganizing arrays

#### 1.7.1 Reshaping

In [2]:
# reshape()
#Reshapes array and returns it
arr = np.array([34, 56, 12, 0, -3, -45, 23, 99])

In [102]:
arr.reshape(4, 2)

array([[ 34,  56],
       [ 12,   0],
       [ -3, -45],
       [ 23,  99]])

In [104]:
arr.reshape(2,2,2)

array([[[ 34,  56],
        [ 12,   0]],

       [[ -3, -45],
        [ 23,  99]]])

In [1]:
import numpy as np

In [4]:
#Unknown dimension
#reshape() allows to have one unknown dimension, in which it will calculate the suitable balue by itself.
#unknown dimension is specified by -1.
arr.reshape(2, 2, -1) # It calculates that -1 as 2.

array([[[ 34,  56],
        [ 12,   0]],

       [[ -3, -45],
        [ 23,  99]]])

In [105]:
arr

array([ 34,  56,  12,   0,  -3, -45,  23,  99])

In [106]:
# resize()
# Same as reshape() but reshapes original array
arr.resize(2, 2, 2)

In [107]:
arr

array([[[ 34,  56],
        [ 12,   0]],

       [[ -3, -45],
        [ 23,  99]]])

In [108]:
#flatten()
# Converts multi-dimensional array into 1D array
# Does not modify original array
arr.flatten()

array([ 34,  56,  12,   0,  -3, -45,  23,  99])

#### 1.7.2 Transposing

In [111]:
arr = np.array([[ 34,  56, 8],
                [ 12,   0, 5]])

In [113]:
np.transpose(arr)

array([[34, 12],
       [56,  0],
       [ 8,  5]])

In [114]:
#Alternate way of transpose
arr.T

array([[34, 12],
       [56,  0],
       [ 8,  5]])

#### 1.7.3 Sorting

In [ ]:
# sort() function is used to sort elements in ascending order

In [120]:
arr1 = np.array([4, 2, 1, 3])
np.sort(arr1)

array([1, 2, 3, 4])

In [124]:
arr2 = np.array([[4, 2, 1],
                 [6, 5, 3]])
np.sort(arr2)

array([[1, 2, 4],
       [3, 5, 6]])

In [122]:
np.sort(arr2)

array([[1, 2, 4],
       [3, 5, 6]])

In [ ]:
#sorting in descending order

In [126]:
np.sort(arr1)[::-1]

array([4, 3, 2, 1])

#### 1.7.4 Concatenating and satcking 

In [139]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

In [140]:
#concatenate(): is used to join arrays along an existing axis.
np.concatenate((arr1, arr2, arr3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
#stack(): is used to join arrays along a new axis.
np.stack((arr1, arr2, arr3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
#hstack(): is used to stack arrays horizontally, column-wise.
np.hstack((arr1, arr2, arr3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
#vstack(): is used to stack arrays vertically, row-wise.
np.vstack((arr1, arr2, arr3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 1.8 Load data from a file

In [156]:
#np.loadtxt()
#np.genfromtxt()
'''Both are used to import data from a file. But genfromtext() method is more flexible and capable of handling data from files 
with irregular structures'''
data = np.genfromtxt('../Datasets/doc.txt', delimiter=',')
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

### 1.9 Changing arrary datatype

In [11]:
#default datatype is int32
arr = np.array([34, 56, 78])
print(arr.dtype)
arr.itemsize

int32


4

##### 1.9.1 Changing datatype during creation

In [12]:
#Changing datatype to int16
arr = np.array([34, 56, 78], dtype='int16')
print(arr.dtype)
arr.itemsize

int16


2

In [13]:
#Changing datatype to int64
arr = np.array([34, 56, 78], dtype='int64')
print(arr.dtype)
arr.itemsize

int64


8

In [16]:
#Changing datatype to int8
arr = np.array([34, 56, 78], dtype='int8')
print(arr.dtype)
arr.itemsize

int8


1

##### 1.9.2 Changing datatype after creation

In [28]:
arr = np.array([34, 56, 78], dtype='int8')
print(arr.dtype)

int8


In [30]:
arr = arr.astype('int32')
arr.dtype

dtype('int32')

#### 1.9.3 Converting array to list

In [75]:
arr = np.array([34, 56, 78, -27, 0])
arr

array([ 34,  56,  78, -27,   0])

In [77]:
li = arr.tolist()
li

[34, 56, 78, -27, 0]

### 1.9 Condition Based Retrieval

In [32]:
arr = np.array([12, 87, 45, 90, -34, 11])

In [21]:
arr[arr > 10]

array([12, 87, 45, 90, 11])

In [33]:
arr2 = np.array([[ 34,  56, 8],
                [ 12,   0, 5]])

In [24]:
arr2[arr2 < 20]

array([ 8, 12,  0,  5])

In [26]:
arr2[arr2 != 34]

array([56,  8, 12,  0,  5])

In [34]:
arr < 30

array([ True, False, False, False,  True,  True])

In [35]:
arr2 != 0 

array([[ True,  True,  True],
       [ True, False,  True]])

In [40]:
~(arr2 != 0) #Negation

array([[False, False, False],
       [False,  True, False]])

In [69]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 2, 6])
arr1 == arr2

array([False,  True, False])

### 2.0 Insertion/Deletion

In [41]:
# Inserting data
# adding single data : insert(arr, index, value)
# adding multiple data : insert(arr, index, list)

In [58]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [60]:
np.insert(arr, 2, 10)

array([ 1,  2, 10,  3,  4,  5])

In [61]:
arr = np.insert(arr, 2, [10, 20, 30])
arr

array([ 1,  2, 10, 20, 30,  3,  4,  5])

In [62]:
# Deleting data
# Deleting single data at specified index : delete(arr, index)
# Deleting multiple data at specified index : delete(arr, list) #The list should contain indices of values to be deleted.

In [63]:
arr

array([ 1,  2, 10, 20, 30,  3,  4,  5])

In [64]:
np.delete(arr, 3)

array([ 1,  2, 10, 30,  3,  4,  5])

In [65]:
arr

array([ 1,  2, 10, 20, 30,  3,  4,  5])

In [66]:
np.delete(arr, [2, 3, 4])

array([1, 2, 3, 4, 5])

In [70]:
arr

array([ 1,  2, 10, 20, 30,  3,  4,  5])

In [71]:
arr.view()

array([ 1,  2, 10, 20, 30,  3,  4,  5])

#### 2.1 Getting Information from any operation

In [84]:
#np.info(operation)

In [85]:
np.info(np.delete)

 delete(arr, obj, axis=None)

Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
`arr[obj]`.

Parameters
----------
arr : array_like
    Input array.
obj : slice, int or array of ints
    Indicate indices of sub-arrays to remove along the specified axis.

    .. versionchanged:: 1.19.0
        Boolean indices are now treated as a mask of elements to remove,
        rather than being cast to the integers 0 and 1.

axis : int, optional
    The axis along which to delete the subarray defined by `obj`.
    If `axis` is None, `obj` is applied to the flattened array.

Returns
-------
out : ndarray
    A copy of `arr` with the elements specified by `obj` removed. Note
    that `delete` does not occur in-place. If `axis` is None, `out` is
    a flattened array.

See Also
--------
insert : Insert elements into an array.
append : Append elements at the end of an array.

Notes
-----
Often it is preferable to use a bool

#### 2.2 Iterating arrays

In [5]:
# nditer() allows to iterate over arrays
arr = np.array([[ 2,  4],
                [ 6,  8],
                [10, 12]])

for x in np.nditer(arr):
    print(x)

2
4
6
8
10
12


#### 2.3 Splitting arrays

In [7]:
# np.array_split() allows to split an array into multiple sub-arrays.
# np.array_split(arr, num)
# num specifies number of subarrays

arr = np.array([12, 2, 5, 7, 10, 33, 4])

np.array_split(arr, 3)

[array([12,  2,  5]), array([ 7, 10]), array([33,  4])]